services:
  - type: web
    name: wms-consultant-agent
    env: node
    plan: free
    buildCommand: npm run install-all && cd client && npm run build && cd ../server
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: false